host: &main_host localhost
port: &main_port 26257
db_connections: &connections
  - db_name: test
    user: test
    host: *main_host
    port: *main_port
    ssl_mode: disable
  - db_name: test
    user: test
    host: *main_host
    port: 26258
    ssl_mode: disable
  - db_name: test
    user: test
    host: *main_host
    port: 26259
    ssl_mode: disable
db_reset_configuration:
  validate_query: "select crdb_internal.zones.zone_name from crdb_internal.zones where crdb_internal.zones.zone_name = '.default'"
  db_connections: *connections
  db_stop_command:
    command: docker
    args:
      - container
      - stop
      - roach1
  db_start_command:
    command: docker
    args:
      - container
      - start
      - roach1
   
