// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package webutil

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockPathRegex is an autogenerated mock type for the PathRegex type
type MockPathRegex struct {
	mock.Mock
}

// Execute provides a mock function with given fields: r
func (_m *MockPathRegex) Execute(r *http.Request) (string, error) {
	ret := _m.Called(r)

	var r0 string
	if rf, ok := ret.Get(0).(func(*http.Request) string); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
