// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package webutil

import mock "github.com/stretchr/testify/mock"

// MockResetDB is an autogenerated mock type for the ResetDB type
type MockResetDB struct {
	mock.Mock
}

// SetDB provides a mock function with given fields: _a0
func (_m *MockResetDB) SetDB(_a0 DBInterface) {
	_m.Called(_a0)
}
