// Code generated by mockery v2.10.0. DO NOT EDIT.

package webutil

import (
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"
)

// MockExecuter is an autogenerated mock type for the Executer type
type MockExecuter struct {
	mock.Mock
}

// Exec provides a mock function with given fields: _a0, _a1
func (_m *MockExecuter) Exec(_a0 string, _a1 ...interface{}) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _a1...)
	ret := _m.Called(_ca...)

	var r0 sql.Result
	if rf, ok := ret.Get(0).(func(string, ...interface{}) sql.Result); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, ...interface{}) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
