// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package webutil

import mock "github.com/stretchr/testify/mock"

// MockRetryCache is an autogenerated mock type for the RetryCache type
type MockRetryCache struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockRetryCache) Execute(_a0 CacheStore) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(CacheStore) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
