// Code generated by mockery v2.10.0. DO NOT EDIT.

package webutil

import mock "github.com/stretchr/testify/mock"

// MockRetryDB is an autogenerated mock type for the RetryDB type
type MockRetryDB struct {
	mock.Mock
}

// Execute provides a mock function with given fields: db
func (_m *MockRetryDB) Execute(db DBInterface) error {
	ret := _m.Called(db)

	var r0 error
	if rf, ok := ret.Get(0).(func(DBInterface) error); ok {
		r0 = rf(db)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
