// Code generated by mockery v2.10.0. DO NOT EDIT.

package webutil

import mock "github.com/stretchr/testify/mock"

// MockRecoverForm is an autogenerated mock type for the RecoverForm type
type MockRecoverForm struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockRecoverForm) Execute(_a0 error) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(error) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
