// Code generated by mockery v2.10.0. DO NOT EDIT.

package webutil

import mock "github.com/stretchr/testify/mock"

// MockEntityRecover is an autogenerated mock type for the EntityRecover type
type MockEntityRecover struct {
	mock.Mock
}

// SetEntity provides a mock function with given fields: _a0
func (_m *MockEntityRecover) SetEntity(_a0 Entity) {
	_m.Called(_a0)
}
