// Code generated by mockery v1.0.0. DO NOT EDIT.

package webutil

import mock "github.com/stretchr/testify/mock"

// MockSendMessage is an autogenerated mock type for the SendMessage type
type MockSendMessage struct {
	mock.Mock
}

// Send provides a mock function with given fields: msg
func (_m *MockSendMessage) Send(msg *Message) error {
	ret := _m.Called(msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Message) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
