// Code generated by mockery v2.10.0. DO NOT EDIT.

package webutil

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockQueryDB is an autogenerated mock type for the QueryDB type
type MockQueryDB struct {
	mock.Mock
}

// Execute provides a mock function with given fields: req, db
func (_m *MockQueryDB) Execute(req *http.Request, db Entity) ([]byte, error) {
	ret := _m.Called(req, db)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(*http.Request, Entity) []byte); ok {
		r0 = rf(req, db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*http.Request, Entity) error); ok {
		r1 = rf(req, db)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
