// Code generated by mockery v1.0.0. DO NOT EDIT.

package webutil

import mock "github.com/stretchr/testify/mock"

// MockDBInterfaceRecover is an autogenerated mock type for the DBInterfaceRecover type
type MockDBInterfaceRecover struct {
	mock.Mock
}

// SetDBInterface provides a mock function with given fields: _a0
func (_m *MockDBInterfaceRecover) SetDBInterface(_a0 DBInterface) {
	_m.Called(_a0)
}
