// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	webutil "github.com/TravisS25/webutil/webutil"
	mock "github.com/stretchr/testify/mock"
)

// DBInterfaceRecover is an autogenerated mock type for the DBInterfaceRecover type
type DBInterfaceRecover struct {
	mock.Mock
}

// SetDBInterface provides a mock function with given fields: _a0
func (_m *DBInterfaceRecover) SetDBInterface(_a0 webutil.DBInterface) {
	_m.Called(_a0)
}
