// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	webutil "github.com/TravisS25/webutil/webutil"
	mock "github.com/stretchr/testify/mock"
)

// EntityRecover is an autogenerated mock type for the EntityRecover type
type EntityRecover struct {
	mock.Mock
}

// SetEntity provides a mock function with given fields: _a0
func (_m *EntityRecover) SetEntity(_a0 webutil.Entity) {
	_m.Called(_a0)
}
