// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockPathRegex is an autogenerated mock type for the PathRegex type
type MockPathRegex struct {
	mock.Mock
}

type MockPathRegex_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPathRegex) EXPECT() *MockPathRegex_Expecter {
	return &MockPathRegex_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: r
func (_m *MockPathRegex) Execute(r *http.Request) (string, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request) (string, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(*http.Request) string); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPathRegex_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockPathRegex_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - r *http.Request
func (_e *MockPathRegex_Expecter) Execute(r interface{}) *MockPathRegex_Execute_Call {
	return &MockPathRegex_Execute_Call{Call: _e.mock.On("Execute", r)}
}

func (_c *MockPathRegex_Execute_Call) Run(run func(r *http.Request)) *MockPathRegex_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request))
	})
	return _c
}

func (_c *MockPathRegex_Execute_Call) Return(_a0 string, _a1 error) *MockPathRegex_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPathRegex_Execute_Call) RunAndReturn(run func(*http.Request) (string, error)) *MockPathRegex_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPathRegex creates a new instance of MockPathRegex. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPathRegex(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPathRegex {
	mock := &MockPathRegex{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
