// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	webutil "github.com/TravisS25/webutil/webutil"
	mock "github.com/stretchr/testify/mock"
)

// QueryDB is an autogenerated mock type for the QueryDB type
type QueryDB struct {
	mock.Mock
}

// Execute provides a mock function with given fields: req, db
func (_m *QueryDB) Execute(req *http.Request, db webutil.Entity) ([]byte, error) {
	ret := _m.Called(req, db)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(*http.Request, webutil.Entity) []byte); ok {
		r0 = rf(req, db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*http.Request, webutil.Entity) error); ok {
		r1 = rf(req, db)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
