// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	webutil "github.com/TravisS25/webutil/webutil"
	mock "github.com/stretchr/testify/mock"
)

// RecoverCache is an autogenerated mock type for the RecoverCache type
type RecoverCache struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *RecoverCache) Execute(_a0 error) (*webutil.ClientCache, error) {
	ret := _m.Called(_a0)

	var r0 *webutil.ClientCache
	if rf, ok := ret.Get(0).(func(error) *webutil.ClientCache); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*webutil.ClientCache)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(error) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
