// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	webutil "github.com/TravisS25/webutil/webutil"
	mock "github.com/stretchr/testify/mock"
)

// ResetDB is an autogenerated mock type for the ResetDB type
type ResetDB struct {
	mock.Mock
}

// SetDB provides a mock function with given fields: _a0
func (_m *ResetDB) SetDB(_a0 webutil.DBInterface) {
	_m.Called(_a0)
}
