// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	webutil "github.com/TravisS25/webutil/webutil"
	mock "github.com/stretchr/testify/mock"
)

// RetryDB is an autogenerated mock type for the RetryDB type
type RetryDB struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *RetryDB) Execute(_a0 webutil.DBInterface) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(webutil.DBInterface) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
