// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	webutil "github.com/TravisS25/webutil/webutil"
	mock "github.com/stretchr/testify/mock"
)

// RetryDB is an autogenerated mock type for the RetryDB type
type RetryDB struct {
	mock.Mock
}

// Execute provides a mock function with given fields: db
func (_m *RetryDB) Execute(db webutil.DBInterface) error {
	ret := _m.Called(db)

	var r0 error
	if rf, ok := ret.Get(0).(func(webutil.DBInterface) error); ok {
		r0 = rf(db)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
