// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	webutil "github.com/TravisS25/webutil/webutil"
	mock "github.com/stretchr/testify/mock"
)

// SendMessage is an autogenerated mock type for the SendMessage type
type SendMessage struct {
	mock.Mock
}

// Send provides a mock function with given fields: msg
func (_m *SendMessage) Send(msg *webutil.Message) error {
	ret := _m.Called(msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(*webutil.Message) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
