// Code generated by MockGen. DO NOT EDIT.
// Source: query_util.go

// Package webutilmock is a generated GoMock package.
package webutilmock

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockFormRequest is a mock of FormRequest interface
type MockFormRequest struct {
	ctrl     *gomock.Controller
	recorder *MockFormRequestMockRecorder
}

// MockFormRequestMockRecorder is the mock recorder for MockFormRequest
type MockFormRequestMockRecorder struct {
	mock *MockFormRequest
}

// NewMockFormRequest creates a new mock instance
func NewMockFormRequest(ctrl *gomock.Controller) *MockFormRequest {
	mock := &MockFormRequest{ctrl: ctrl}
	mock.recorder = &MockFormRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFormRequest) EXPECT() *MockFormRequestMockRecorder {
	return m.recorder
}

// FormValue mocks base method
func (m *MockFormRequest) FormValue(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormValue", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// FormValue indicates an expected call of FormValue
func (mr *MockFormRequestMockRecorder) FormValue(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormValue", reflect.TypeOf((*MockFormRequest)(nil).FormValue), arg0)
}
